#logout:
#    path: /logout
#login_check:
#    path: /login_check

base_path:
    path:   /
    defaults:
        _controller: FrameworkBundle:Redirect:urlRedirect
        path: /pl
        permanent: true

logout:
    path: /logout

app:
    resource: @AppBundle/Controller/
    type:     annotation
    prefix:    "/{_locale}"
