security:
    encoders:
        AppBundle\Entity\User: plaintext

    providers:
        database_users:
            entity: { class: AppBundle:User}

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt|error)|css|images|js)/
            security: false

        secured_area:
                    pattern: ^/
                    anonymous: true
                    form_login:
                             check_path: login_check
                             login_path: login_form
                    logout:
                             path: /logout
                             target: login_form

    access_control:

           - { path: ^/../login, role: IS_AUTHENTICATED_ANONYMOUSLY }
           - { path: ^/, role: ROLE_USER }