# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
  entity_author.listener:
    class: AppBundle\EventListener\EntityAuthor
    tags:
      - { name: doctrine.event_listener, event: prePersist }
    arguments:
      - "@security.token_storage"
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]


    app.form.type.task:
        class: AppBundle\Form\Type\TaskType
        arguments: [@security.token_storage]
        tags:
            - { name: form.type, alias: task }
