AppBundle\Entity\User:
    properties:
        email:
            - NotBlank: ~
            - Email:
                message: The email "{{ value }}" is not a valid email.
                checkMX: true
            - Length:
                min: 3
                max: 100
        name:
            - NotBlank: ~
            - Length:
                min: 3
                max: 40
        password:
            - NotBlank: ~
            - Length:
                min: 6
                max: 20